[package]
name = "gist"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
clap = { version = "4.0", features = ["derive"] }

[[bin]]
name = "gist"
path = "src/main.rs"